- pkg/leader/leader.go
Also includes whitespace changes due to gofmt
> Update dev mode env var to CATTLE_DEV_MODE

- pkg/apply/apply.go
- pkg/apply/desiredset.go
- pkg/apply/fake/apply.go
- pkg/gvk/get.go
This new method is implemented in desiredSet to pass in a known
set of gvks to manage previously created resources.
> Add WithGVK() method to Apply interface

- pkg/controller-gen/generators/type_go.go
> Properly compare and mutate status

- pkg/summary/summarizers.go
Adding a new error types to be used for catalogs
**Issue:**
https://github.com/rancher/rancher/issues/24914
> Add error summarizer

- pkg/controller-gen/generators/type_go.go
I am still testing this change locally, but appears to be working as expected.
> Update lastUpdatedTime for StatusHandler when Status Changes

- pkg/git/git.go
https://github.com/rancher/wrangler/issues/144
> Remove assumed 'master' branch from git clone when called from Ensure

- pkg/summary/summarizers.go
Fixing summarizing of CNCF Rook project custom resources including CephCluster and io.objectbucket.v1alpha1.ObjectBucketClaim. This PR fixes issues https://github.com/rancher/wrangler/issues/148 and https://github.com/rancher/wrangler/issues/149.
> Fix summarizing of CNCF Rook resources

- pkg/crd/init.go
Related to https://github.com/rancher/wrangler/pull/157
This adds a function to the CRD creation to check and see if the CRD already exists, if it does and the preserveUnknownFields is set to true, then it patches it to false before applying the newly generated CRDs.
> patch crd to set preserveUnknownFields to false

- pkg/apply/apply.go
- pkg/apply/desiredset.go
- pkg/apply/desiredset_crud.go
- pkg/apply/desiredset_process.go
- pkg/apply/fake/apply.go
Relevant issue: https://github.com/rancher/rancher/issues/33203
This PR would ensure that certain GVKs are not deleted for desiredset applys.
> Add noDeleteGVK

- README.md
Wrangler v1.0 was tagged and released.
Related to #208 #205
> Remove beta from README

- pkg/leader/leader.go
The leader election code would always terminate fatally, with a non-zero exit code. Even if the application requested a shutdown. This was common when paired with wrangler-cli setting up a content that canceled when SIGTERM was detected. SIGTERM is sent when a node shuts down to tell the processes to exit, for example. The non-zero exit code is then recorded as an error by Kubernetes.
Instead, when an exit is requested because the context is set to done wrangler can cleanly exit. This is a pattern found in the kube scheduler
Relates to https://github.com/rancher/fleet/issues/1096 
SURE-5492
> leaderelection: exit 0 when exit requested

- pkg/generated/controllers/networking.k8s.io/v1/networkpolicy.go
Made issue for adding script that checks for this: https://github.com/rancher/wrangler/issues/243
> go generate

- go.mod
- go.sum
- pkg/controller-gen/generators/factory_go.go
- pkg/generated/controllers/admissionregistration.k8s.io/factory.go
- pkg/generated/controllers/apiextensions.k8s.io/factory.go
- pkg/generated/controllers/apiregistration.k8s.io/factory.go
- pkg/generated/controllers/apps/factory.go
- pkg/generated/controllers/batch/factory.go
- pkg/generated/controllers/coordination.k8s.io/factory.go
- pkg/generated/controllers/core/factory.go
- pkg/generated/controllers/extensions/factory.go
- pkg/generated/controllers/networking.k8s.io/factory.go
- pkg/generated/controllers/rbac/factory.go
- pkg/generated/controllers/storage/factory.go
**Issue:**
https://github.com/rancher/rancher/issues/40021
**Original PR:**
https://github.com/rancher/wrangler/pull/248
> [Forwardport] v2.7: Add function to copy factory and add user agent

- go.mod
- go.sum
https://github.com/rancher/rancher/issues/41840
> [ k8s 1.27 ] update lasso to latest

- .github/workflows/lint.yaml
- pkg/apply/fake/apply.go
- pkg/controller-gen/generators/type_go.go
- pkg/controller-gen/generators/util.go
- pkg/generated/controllers/apiextensions.k8s.io/v1/customresourcedefinition.go
- pkg/generated/controllers/apiregistration.k8s.io/v1/apiservice.go
- pkg/generated/controllers/apps/v1/daemonset.go
- pkg/generated/controllers/apps/v1/deployment.go
- pkg/generated/controllers/apps/v1/statefulset.go
- pkg/generated/controllers/batch/v1/job.go
- pkg/generated/controllers/core/v1/namespace.go
- pkg/generated/controllers/core/v1/node.go
- pkg/generated/controllers/core/v1/persistentvolume.go
- pkg/generated/controllers/core/v1/persistentvolumeclaim.go
- pkg/generated/controllers/core/v1/pod.go
- pkg/generated/controllers/core/v1/service.go
- pkg/generated/controllers/extensions/v1beta1/ingress.go
- pkg/generated/controllers/networking.k8s.io/v1/networkpolicy.go
- pkg/generic/generating.go
- pkg/generic/generating_test.go
> [release-2.0] Allow GeneratingHandlers to skip Apply if resource version didn't change

- .github/workflows/lint.yaml
- pkg/apply/desiredset.go
- pkg/apply/desiredset_apply.go
- pkg/apply/desiredset_process.go
- pkg/apply/desiredset_process_test.go
> [release-2.1] Use indexer when listing cached types by hash

- .github/workflows/lint.yaml
- pkg/apply/desiredset.go
- pkg/apply/desiredset_apply.go
- pkg/apply/desiredset_process.go
- pkg/apply/desiredset_process_test.go
Backport of https://github.com/rancher/wrangler/pull/326
> [release-2.0] Use indexer when listing cached types by hash

- pkg/relatedresource/changeset.go
- pkg/relatedresource/changeset_test.go
Fixes https://github.com/rancher/rancher/issues/44642, backported from https://github.com/rancher/wrangler/pull/361
See original PR for details
> [v2.1] fix(relatedresource): remove event handlers when context is closed

- pkg/relatedresource/changeset.go
- pkg/relatedresource/changeset_test.go
Fixes rancher/rancher#44641, backported from #361
See original PR for details
> [v2.0] fix(relatedresource): remove event handlers when context is closed

- CODEOWNERS
Issue: https://github.com/rancher/rancher/issues/44840
> [backport 2.0] Add codeowners file

- go.mod
- go.sum
> Upgrade lasso to b2a060d103c1a89cf502216d2e7d51ef7fe0a155

- .github/renovate.json
- .github/workflows/ci.yaml
- .github/workflows/lint.yaml
> Update branches for CI

- .github/workflows/release.yaml
- README.md
- VERSION.md
https://github.com/rancher/rancher/issues/46900
> Implement versioning ADR

- .github/workflows/release.yaml
- README.md
- VERSION.md
https://github.com/rancher/rancher/issues/46900
> [release/v2] Implement versioning ADR

- .github/renovate.json
Issue:  https://github.com/rancher/rancher/issues/46900
> Update renovate.json to reference main and release/v2

- pkg/generic/factory.go
Fixes: #559 
This commit ensures that the values returned to `factory.Sync` are not ignored, ensuring better troubleshooting experience.
> Improves error handling for factory.Sync

- go.mod
- go.sum
https://github.com/rancher/rancher/issues/49299
Bumping lasso dep to bring fix for issue above into wrangler.
> [main] Bump lasso

- pkg/summary/gvk.go
- pkg/summary/gvk_test.go
- pkg/summary/summarizers.go
- pkg/summary/summarizers_test.go
> #48559 - Added GVK check errors

- pkg/schemas/reflection.go
- pkg/schemas/types.go
Related to:  https://github.com/rancher/rancher/issues/45827
> [main] Add ResourcePermissions to Schema type definition

- VERSION.md
Issue:  https://github.com/rancher/rancher/issues/48796
> Update VERSION to include k8s v1.33
