rancher/wrangler

pkg/apply/desiredset_process.go
**Describe the bug**
While deploying the [local path provisioner](https://github.com/rancher/local-path-provisioner/blob/master/deploy/local-path-storage.yaml) with k3s using the addon controller / static manifests I encountered the following behavior:
- when the addon controller discovers and applies the manifest for the first time, the deployment succeeds as expected and all objects are successfully created on the api server
- when the addon controller tries to apply the manifest a second time (e.g. when the addon object is deleted, when the manifest changes, ...), objects that do not have namespace scope (e.g. `ClusterRole` or `ClusterRoleBinding`) but reference a namespace in their metadata (e.g. `local-path-provisioner-role` or `local-path-provisioner-bind`) are handled incorrectly. …
=> Applying cluster-scoped objects with namespace metadata reveals unexpected behavior

pkg/apply/desiredset_compare.go, pkg/apply/desiredset_crud.go, pkg/apply/desiredset_process.go
This address an issue in rancher/system-upgrade-controller#25 when generating objects `WithNoDelete()` where the replace logic fails with noisy 'Replace Wait' errors in the log.
This also mitigates the no-delete+replace logic swamping the rate limit for a custom type.
=> fix spurious replace wait errors

pkg/summary/informer/informer.go
Problem:
In a cluster with a large number of a single object, say 10k large
secrets, when the controller starts it attempts to list all of those
secrets and hits the client timeout
Solution:
Just increasing the client timeout does not work as the API server also
has a timeout. The API server ignores the limit when resourceVersion is
set to 0 which causes the call to take longer than either timeout
(running curl against the API server the call was taking over 3min on
average and pulling approx 2GB of data) so if resourceVersion is set to
0 reset it to empty string
=> Drop resourceVersion on lists when set to 0

pkg/yaml/yaml.go
Prior, the error returned from the gvk package Get function was
not included in the returned error. This error may contain
actionable advice on resolving the error. For example, suggesting
that the user import the generated controller package so that its
init function is called.
=> Wrap error from gvk

pkg/schemas/openapi/generate.go
This commit addes allow: true so that when comparing crd generated from
wranger code and crd from api server, where api server/client-go will modify the
field to true.
=> Fix crd generation code

pkg/git/git.go
Use "git -c" to adopt http basic auth from env variables to avoid
reading password from URL. Pass password to stdin doesn't work as we
disabled git prompt.
=> Fix http auth

pkg/crd/init.go
allow custom singular name as some CRDs like NAD has variant name definitions https://github.com/intel/multus-cni/blob/36d3874c4c987affb101bbac8b2d69b4429266df/images/multus-daemonset.yml#L2-L14
=> Add custom singular name

pkg/name/name.go
If the name is bigger than 63 characters the name is cut and the last character might violate the regexp check for valid k8s name.
Added a check for the last character in SafeConcatName to remedy this.
Resolves [issue](https://github.com/rancher/system-upgrade-controller/issues/110)
Signed-off-by: Birol Bilgin <birolbilgin@gmail.com>
=> added check in SafeConcatName

pkg/crd/init.go, pkg/schemas/openapi/generate.go
Totally stealing code from @ibuildthecloud that he gave me but this adds default tag support to wrangler with one big caveat.
The caveat is that you have to set `crd.spec.preserveUnknownFields` to `false` but you CANNOT do this at the same time as adding a schema that has defaults defined :(
You must first set `preserveUnknownFields` to `false` then you can apply the CRD with defaults which is set to true by default in v1beta1 it seems.
**Question:** would it make sense to modify the crd/init.go to look at the existing CRD and patch `preserveUnknownFields` if set to true before applying the newly generated CRD definition? Maybe this is an option on the CRD customization?  (See PR https://github.com/rancher/wrangler/pull/158)
**Question:** do we need to add a …
=> adding default support

pkg/crd/init.go
Return if error is not-found, otherwise it will patch a non-existing crd which will return error.
=> Return if crd is not found, use v1 client

pkg/summary/condition.go
This partially reverts commit 3eba78f45e7d61364efd11d73334641c17305b4c.
This reverts commit 3533ace946aaf8cc64ae4be9ead3221c35975884.
The changes to the condition message formatting were not really helpful,
since the condition summary gets translated to a TransitioningMessage,
which does not always make sense when it shows up in the UI.
https://github.com/rancher/rancher/issues/32165
=> Revert condition formatting changes

go.mod, go.sum
Update the lasso version before cutting wrangler `v0.8.1`
Relevant issue:
- https://github.com/rancher/rancher/issues/33429
=> [master] Update lasso version

pkg/webhook/router.go
These changes add access logs to webhook handlers with a middleware pattern. The logs have format that looks like:
```
DEBU[0003] CREATE management.cattle.io/v3.GlobalRole gr-wgmzb user=user-j9rfg allowed=false err=<nil> 
```
To enable, applications using the webhook package need to set logrus to the debug level
=> Add debug logging around webhook handler invocation

pkg/crd/init.go
- https://github.com/rancher/rancher/issues/33586
- https://github.com/rancher/rancher/issues/33112
- https://github.com/rancher/fleet/issues/451
This PR adds apiext `v1beta1` CRD conversion (from apiext `v1` CRDs) for upgrade scenarios.
Event though apiext CRD `v1beta1` is being removed in k8s 1.22.0, Rancher must handle upgrade scenarios from k8s <= 1.15.x clusters.
- design goal: do not change anything (or as little as possible) about how users create v1 CRDs (consumers should not even notice this change)
- conversion is preferred over re-addition: https://github.com/rancher/wrangler/pull/171#issuecomment-882896507
=> Add CRD v1 to v1beta1 converter

pkg/summary/summarizers.go
This was removed as a part of https://github.com/rancher/wrangler/commit/3eba78f45e7d61364efd11d73334641c17305b4c. Not sure if it was intentional, but this causes state to be Active for RKE1 nodes (and maybe clusters) even if the conditions have the right information. 
Issue: 
https://github.com/rancher/rancher/issues/32891
=> add ready state to summarizer

pkg/webhook/router.go
Small improvement- returning error and also logging it at error level (if there is a situation where a request doesn't match any routes)
Example output: `ERRO[0025] no route match found for CREATE management.cattle.io/v3, Kind=GlobalRole gr-v9cg2 `
=> Better error handling and logging for webhook

pkg/signals/signal.go
trying to get this shutdown func to use from windows service manager to cancel context when a service is stopped via Stop-Service in powershell.
source: https://github.com/kubernetes/kubernetes/blob/da707b6133ff0c66dc4d24295374e7e5de8852f5/staging/src/k8s.io/apiserver/pkg/server/signal.go#L59-L69
example usage: https://github.com/kubernetes/kubernetes/blob/da707b6133ff0c66dc4d24295374e7e5de8852f5/pkg/windows/service/service.go#L82-L87
=> adding the RequestShutdown func from upstream

go.mod, go.sum, pkg/apply/desiredset_process.go, pkg/apply/desiredset_process_test.go, pkg/objectset/objectset.go, pkg/objectset/objectset_test.go
https://github.com/rancher/rancher/issues/34712
When users try  to modify resources in multiple namespaces wrangler attempts to list them across all namespaces.  Most users do not have permission to list resources across all namespaces and an error is returned.
When applying resources gather what namespaces will be affected make multiple searches across the specified namespaces.
I tested this and confirmed users will still see permission errors if they attempt to create a resource in a namespace that they do not have access to.  I also  tested creating resources that are not namespaced with a user that has access to them.
=> fixed permissions errors when applying multiple namespaces

pkg/apply/desiredset_process.go, pkg/apply/desiredset_process_test.go
https://github.com/rancher/rancher/issues/35656
The issue is caused by https://github.com/rancher/wrangler/pull/183 resolving distinct namespaces based on objects from all GVKs included into apply manifest instead of objects of GVK being processed in the current `process` iteration. The PR addresses this issue.
Note the linked PR implemented `ObjectSet.Namespaces` which is no longer needed. However, decided to leave it in since it's exported function of a library that made it into a release and it has good test coverage - there is a chance it will be useful for something else.
=> Fixed distinct namespaces resolution in Apply

pkg/controller-gen/generators/client_generator.go
TrimRight isn't the right function to use here, in fact it can cause all sorts of unwanted behavior because the cutset is going to be something like `/v1` or `/v1beta1` and TrimRight will remove any of the characters regardless of order (at least how I understand it) from the right if they exist. 
We actually only want to TrimSuffix when it specifically matches `/+gv.Version` so `/v1` or `/v1beta1` etc.
I was using `project.ekristen.dev` when this code was generating `project.ekristen.de` because it was Trimming right `/v1` from `project.ekristen.dev/v1` so it was removing extra v because the cutset is `/v1`
=> fix: TrimRight removes an extra character in certain conditions

pkg/summary/summary.go
If a summary message had two or more empty strings, then they would all be
removed on deduplication. After this change, if a summary message has a single
empty string, then that empty string is also removed.
=> Remove empty strings from summary messages

pkg/schemas/reflection.go
Fixes harvester [issue 1919](https://github.com/harvester/harvester/issues/1919)
Add type checks for omitted but reasonably likely to be used types `uint` and `uintptr` during field type inspection.
=> add checks for uint and uintptr when inspecting schema fields

pkg/summary/summarizers.go
Related issue: https://github.com/rancher/rancher/issues/36993
In order to make a better and more consistent experience in Rancher's
UI, some objects will now go into a Reconciled unknown state. In order
for this to showup properly in the UI, this condition needs to be added
to the list of TransitioningUnknown conditions. This change does exactly
that.
=> Add Reconciled condition to TransitioningUnknown

go.mod, pkg/apply/apply.go, pkg/apply/reconcilers.go
update reconciler for job to get a new pruned obj back to avoid 64 byte truncated annotations
=> fix truncated job annotations

go.mod
When running go test there is a message about dependencies and to
run go mod tidy. This change does just that.
=> Updating the go.mod to include indirect deps

README.md, pkg/webhook/match.go, pkg/webhook/router.go
To create effective tests in supported projects, callers need
the ability to create a valid webhook.Request which involves
setting the ObjectType.
=> Adds webhook documentation and makes Request fully public.

pkg/leader/leader.go
I found it useful to leverage the `CATTLE_DEV_MODE` environment variable in order to make leader leases last longer - this is pretty much needed when attaching a debugger (eg. [via delve](https://github.com/moio/delve-debugger)) - else the process is automatically killed after some seconds.
Problem with `CATTLE_DEV_MODE` in that scenario is, at the moment, that it also elongates the retry period, which means the initial leader election at process start will also take two hours, which is a bit impractical.
This PR tries to address the issue by elongating all times but the retry period - I tested it manually and it works great for delve debugging.
Related: #234 
Issue: https://github.com/rancher/rancher/issues/39506
=> Leader election: do not wait 2 hours for retry, even in dev mode

pkg/condition/condition.go
#252
Add checks from [`87c25c8` (#77)](https://github.com/rancher/wrangler/pull/77/commits/87c25c813af5e245bc035112dd01fed1d77951a8) to `CreateUnknownIfExists`
=> Fix CreateUnknownIfNotExists to work on status objects

pkg/git/git.go
Porting git reset fix from release branches to master
https://github.com/rancher/wrangler/pull/261
=> Fix git reset command

.drone.yml, .github/dependabot.yaml, .github/workflows/lint.yaml
The GitHub Action can display, right in the code (i.e. PR), where the lint issue is at. This can provide more direct feedback to PR authors.
Note, dependabot will create PRs for the GitHub Action but not for the version of the linter that's specified in the configuration.
=> Moving linting to GitHub Actions

pkg/name/name.go
* The func will crash with a runtime error for count <= 5.
* If count is 6, the result will have a leading dash.
* If len(string) == count, it will not return the original string, instead it appends a hash.
=> Add documentation to name.Limit

pkg/schemas/openapi/generate.go
The IntOrString type is currently generated as a string, which is incorrect. It should use the XIntOrString bool to specify that either integer or string values are allowed.
Ref: https://github.com/kubernetes/apiextensions-apiserver/blob/v0.24.0/pkg/apis/apiextensions/v1/types_jsonschema.go#L107-L120
There was even a TODO in the code for fixing this once apiextensions hit v1.
Fixes an issue where IntOrString fields with integer values are rejected with messages like:
`The HelmChart "cert-manager" is invalid: spec.set.webhook.timeoutSeconds: Invalid value: "integer": spec.set.webhook.timeoutSeconds in body must be of type string: "integer"`
`spec.set` is an IntOrString field, but the wrangler-generated openapi v3 schema rejects it as described above.
* …
=> Fix schema generation for IntOrString

pkg/leader/leader.go, pkg/leader/leader_test.go
We have observed in `fleet-agent` user cases ([SURE-6125](https://jira.suse.com/browse/SURE-6125)/[fleet#1465](https://github.com/rancher/fleet/issues/1465)) that the leader election can be lost due to timeouts - not because pods are not working, but because the control plane is overwhelmed by load.
While of course having an overloaded control plane is a problem in and of itself, losing the election means that Wrangler-based pods will restart, which in turn means a new full listing of all interesting resources, creating additional load and exacerbating symptoms.
Ideally, the situation should improve when [API Priority and Fairness](https://kubernetes.io/docs/concepts/cluster-administration/flow-control/) goes out of beta and becomes commonplace - as it should ensure leader election API …
=> leaderelection: configure all timeouts via environment variables

.github/workflows/lint.yaml, pkg/apply/desiredset.go, pkg/apply/desiredset_apply.go, pkg/apply/desiredset_process.go, pkg/apply/desiredset_process_test.go
Relates to rancher/fleet#1842
Extending `WithCacheType` option, those types will be indexed by their hash label (`objectset.rio.cattle.io/hash`), which every object produced or modified by `Apply` has. This is a direct replacement for using `List` with an exact label selector, which is certainly more expensive.
The ultimate goal of this change is reducing CPU usage, which has been successfully observed by testing this change in a custom Fleet build (along with rancher/fleet#1857), where in some cases produced around 40%-50% CPU drop (see SURE-6990).
=> Use indexer when listing cached types by hash

.github/workflows/lint.yaml, pkg/apply/fake/apply.go, pkg/controller-gen/generators/type_go.go, pkg/controller-gen/generators/util.go, pkg/generated/controllers/apiextensions.k8s.io/v1/customresourcedefinition.go, pkg/generated/controllers/apiregistration.k8s.io/v1/apiservice.go, pkg/generated/controllers/apps/v1/daemonset.go, pkg/generated/controllers/apps/v1/deployment.go, pkg/generated/controllers/apps/v1/statefulset.go, pkg/generated/controllers/batch/v1/job.go, pkg/generated/controllers/core/v1/namespace.go, pkg/generated/controllers/core/v1/node.go, pkg/generated/controllers/core/v1/persistentvolume.go, pkg/generated/controllers/core/v1/persistentvolumeclaim.go, pkg/generated/controllers/core/v1/pod.go, pkg/generated/controllers/core/v1/service.go, pkg/generated/controllers/extensions/v1beta1/ingress.go, pkg/generic/generating.go, pkg/generic/generating_test.go
Extends `GeneratingHandlerOptions` to allow a new `UniqueApplyForResourceVersion`, which will keep track of the latest resource version for each individual resource that was handled, avoiding subsequent calls to Apply if the first one was successful. The goal is to limit the number of Apply is called with the same inputs, reducing the computation costs. However, this means that handlers must be deterministic, in the sense that they must produce the same object list for the same input resource, hence this option must be carefully enabled on a case by case basis. It has no impact on other users if the option is not enabled.
We have successfully tested this feature on Fleet's Bundle and GitRepo generating handlers (see rancher/fleet#1964 for an example usage), while trying to mitigate the …
=> Allow GeneratingHandlers to skip Apply if resource version didn't change

pkg/apply/desiredset.go, pkg/apply/desiredset_apply.go, pkg/apply/desiredset_process.go, pkg/apply/desiredset_process_test.go
Relates to rancher/fleet#1842
Backport of #326 (cherry-pick + only adapting the correct import paths). That pull request was in fact originally forward-ported from v1, as that is what Fleet 0.7 and Fleet 0.8 uses. This makes this patch the closest to what was already tested by some users on their testing and production setups (using a debug build).
In other words, this backport (and subsequent new v1 release) is necessary in order to use this change on Fleet, since the current release branches still use wrangler/v1, and upgrading to v2 is not feasible.
=> [v1.1] Use indexer when listing cached types by hash

.github/workflows/lint.yaml, pkg/apply/fake/apply.go, pkg/controller-gen/generators/type_go.go, pkg/controller-gen/generators/util.go, pkg/generated/controllers/apiextensions.k8s.io/v1/customresourcedefinition.go, pkg/generated/controllers/apiregistration.k8s.io/v1/apiservice.go, pkg/generated/controllers/apps/v1/daemonset.go, pkg/generated/controllers/apps/v1/deployment.go, pkg/generated/controllers/apps/v1/statefulset.go, pkg/generated/controllers/batch/v1/job.go, pkg/generated/controllers/core/v1/namespace.go, pkg/generated/controllers/core/v1/node.go, pkg/generated/controllers/core/v1/persistentvolume.go, pkg/generated/controllers/core/v1/persistentvolumeclaim.go, pkg/generated/controllers/core/v1/pod.go, pkg/generated/controllers/core/v1/service.go, pkg/generated/controllers/extensions/v1beta1/ingress.go, pkg/generic/generating.go, pkg/generic/generating_test.go
=> [release-2.1] Allow GeneratingHandlers to skip Apply if resource version didn't change

.github/renovate.json
Continuation of https://github.com/rancher/rancher/issues/44968
Renovate supports the ability to target multiple base branches. It will update the dependencies of those branches separately, so we don't have to backport any dependency fixes. 
More information on this renovate feature can be found here:
https://docs.renovatebot.com/configuration-options/#basebranches
=> Support multiple base branches with renovate

pkg/data/values.go, pkg/data/values_test.go
Add the ability to use an index number to get an item out of a slice.
The number will still be a string representation of an integer. For
example, to get the last element from a nested slice like:
```
data := map[string]interface{}{
"data": []interface{}{
"first",
"second",
"third",
},
}
```
Use keys like
```
val := GetValues(data, "dat", "2")
```
https://github.com/rancher/rancher/issues/42767
=> Add support for getting array index in GetValue

pkg/name/name.go, pkg/name/name_test.go
Just some minor tech debt. Add comments to each of the exported functions. A lot of these functions are not great (would prefer to return errors), but since they're exported we should at minimum provide comments.
I added some unit tests to `SafeConcatName` because I've used it extensively elsewhere so I want to make sure it doesn't get broken accidentally.
=> Add unit tests and comments to the name package

pkg/signals/signal.go
I've used debug builds that included this patch and was proved to be very useful to identify the cause of Rancher restarts, as it makes it immediately obvious that Kubernetes is terminating the container.
=> Log received signals used for context cancelation

.golangci.json, go.mod
When updating BRO for 1.32, I found that the current config caused the CI to be brittle as it required a specific GO 1.23 release. Specifically the error I was encountering is:
>  go.mod requires go >= 1.23.3 (running go 1.23.2; GOTOOLCHAIN=local)
This change should allow for `1.23.2` (and older 1.23) to work without errors.
=> Adjust go.mod values for go/toolchain

pkg/data/values.go, pkg/data/values_test.go
I discovered this while working on issue [#42767](https://github.com/rancher/rancher/issues/42767) -- steve failed to sort on a value in a string array in non-sql mode, and then I saw that `GetValueFromAny` here in wrangler wasn't handling string arrays, and needed some improvement (like missing `else-blocks` to handle unexpected cases, duplicated handling of the end of a list.
There will be a steve PR once this is in.
=> Fix and tighten up 'GetValueFromAny'
